# -*- coding: utf-8 -*-
"""PHASE 34 master audio inventory.

One row per Freesound ID. Drives:
  * assets/audio/AUDIO_INDEX.md
  * the ffmpeg runtime-copy build
  * the AUDIO_ASSETS manifest pasted into game.html

Columns:
  id        Freesound id (also the filename prefix — never renamed)
  cat       index category
  use       likely gameplay use (one line, index copy)
  key       logical manifest id, or None when the asset is catalogued but not wired
  kind      'sfx' | 'bed' | 'step' — decides the runtime encode
"""

# cat keys, in index order
CATS = [
  ('interior',   'Interior / home ambience'),
  ('haven',      'Haven'),
  ('footsteps',  'Footsteps'),
  ('doors',      'Doors, furniture and objects'),
  ('forest',     'Forest'),
  ('farmlands',  'Farmlands'),
  ('animals',    'Animals'),
  ('weather',    'Weather'),
  ('water',      'Water'),
  ('suburbia',   'Suburbia'),
  ('electrical', 'Electrical / hum'),
  ('rift',       'Rift / reality distortion'),
  ('stalker',    'Stalker'),
  ('tension',    'Horror tension'),
  ('bloodnight', 'Blood Night'),
  ('behemoth',   'Hollowed Behemoth'),
  ('vanish',     'Haven disappearance'),
  ('finale',     'Final creature / finale'),
  ('ui',         'UI / interaction'),
  ('impact',     'Impacts and stings'),
  ('voice',      'Voices, whispers and breath'),
  ('unwired',    'Catalogued, not wired'),
]

A = [
 # ---- interior / home -----------------------------------------------------------
 ('511688','interior','Farmhouse / Disconnected Home interior room tone.','bed.interior.house','bed'),
 ('751329','interior','Suburbia house interior room tone — the quietest of the three.','bed.interior.quiet','bed'),
 ('714170','interior','Basement / cellar room tone; under-floor spaces.','bed.interior.basement','bed'),
 ('416002','interior','House ambience with a clock — Suburbia living rooms.','bed.interior.clock','bed'),
 ('805394','interior','Room tone with weather on the window. The Haven room layer.','bed.haven.room','bed'),
 ('790019','interior','Old clock tick sequence — loops as an interior detail layer.','bed.interior.tick','bed'),
 ('328067','interior','Broken grandfather clock, inconsistent ticking. Wrong-house rooms.','sfx.clock.wrong','sfx'),
 ('342926','interior','Old clock pendulum. NONCOMMERCIAL.','sfx.clock.pendulum','sfx'),
 # ---- haven ---------------------------------------------------------------------
 ('387128','haven','The Haven hearth. The fire layer, and the second thing taken away.','bed.haven.hearth','bed'),
 ('259228','haven','Outdoors beyond the cabin — the Haven outside layer, taken away first.','bed.haven.outside','bed'),
 ('829081','haven','Still outdoor air, authored as a loop. Calm exterior anywhere.','bed.air.still','bed'),
 # ---- footsteps -----------------------------------------------------------------
 ('813621','footsteps','Dirt / grass / soil steps. Overworld and Farmland default.','step.soft','step'),
 ('807862','footsteps','Steps on grass.','step.grass','step'),
 ('352870','footsteps','Steps on dirt and gravel — roads and farm tracks.','step.gravel','step'),
 ('530384','footsteps','Boots on gritty ground, stones and leaves. Forest floor.','step.leaves','step'),
 ('548384','footsteps','Boots in mud — wet Farmland soil, pond margins.','step.mud','step'),
 ('813622','footsteps','Steps on stone, rock and concrete. Suburbia paving, stone.','step.stone','step'),
 ('682773','footsteps','Walking on pavement — Suburbia streets.','step.pavement','step'),
 ('366111','footsteps','Indoor footsteps — interiors on boards.','step.wood','step'),
 ('459970','footsteps','Footsteps on hollow wood — porches, barn floors.','step.hollow','step'),
 ('830503','footsteps','Walking upstairs.','step.stairs','step'),
 ('19263','footsteps','Generic step sequence. AIFF — runtime copy required.','step.plain','step'),
 # ---- doors, furniture, objects --------------------------------------------------
 ('213406','doors','Wooden door opening. The default door-open cue.','sfx.door.open','sfx'),
 ('213404','doors','Wooden door closing with a latch. The default door-close cue.','sfx.door.close','sfx'),
 ('432562','doors','A second door-open take, for variation.','sfx.door.open2','sfx'),
 ('340046','doors','Heavier wood door closing.','sfx.door.close2','sfx'),
 ('858958','doors','Squeaky door opening and closing — abandoned structures.','sfx.door.squeak','sfx'),
 ('848616','doors','Wooden screen door — the farmhouse porch door.','sfx.door.screen','sfx'),
 ('583119','doors','A long door creak. Used as a slow creak, not a door cue.','sfx.creak.long','sfx'),
 ('704612','doors','Door creak, close mic.','sfx.creak.door','sfx'),
 ('534337','doors','Door interaction handle rattle.','sfx.door.handle','sfx'),
 ('841281','doors','Single door knock.','sfx.knock.near','sfx'),
 ('728214','doors','Knock on door, sequence.','sfx.knock.seq','sfx'),
 ('186517','doors','Distant wooden door knock and open — heard from another room.','sfx.knock.distant','sfx'),
 ('450791','doors','Distant door slam with room boom. Suburbia anomaly.','sfx.door.slam','sfx'),
 ('440869','doors','A doorbell, far off. Suburbia anomaly.','sfx.doorbell','sfx'),
 ('364106','doors','Wooden drawer open and close.','sfx.drawer','sfx'),
 ('421033','doors','Desk cabinet door close.','sfx.cabinet','sfx'),
 ('470619','doors','Bathroom cabinet opening.','sfx.cabinet2','sfx'),
 ('415939','doors','Wooden chair.','sfx.chair','sfx'),
 ('654148','doors','Plastic chair dragged over brick — yards and porches.','sfx.chair.drag','sfx'),
 ('766645','doors','Couch creak. NONCOMMERCIAL.','sfx.couch','sfx'),
 ('238288','doors','A quiet creak — furniture settling.','sfx.creak.quiet','sfx'),
 ('502505','doors','Single wood creak.','sfx.creak.a','sfx'),
 ('506665','doors','Single wood creak, second take.','sfx.creak.b','sfx'),
 ('796507','doors','Wood friction creak.','sfx.creak.c','sfx'),
 ('261371','doors','ONE floor board. This is the Phase 31 occupancy footfall.','sfx.floor.single','sfx'),
 ('822745','doors','Wood floor creak sequence.','sfx.floor.seq','sfx'),
 ('570864','doors','Creaking boards.','sfx.floor.boards','sfx'),
 ('264014','doors','Metal door groaning — barn doors, gates.','sfx.metal.groan','sfx'),
 ('481787','doors','Short metallic groan.','sfx.metal.groan2','sfx'),
 ('863059','doors','Knuckles on a metal box — machinery, tanks, the water tower.','sfx.metal.knock','sfx'),
 ('617608','doors','Light switch click.','sfx.switch','sfx'),
 ('423512','doors','Light switch on and off.','sfx.switch2','sfx'),
 # ---- forest ---------------------------------------------------------------------
 ('803224','forest','Birds, faint room tone, breeze through trees. THE Overworld day bed.','bed.overworld.day','bed'),
 ('496512','forest','Bright forest ambience — the calm Overworld variant.','bed.overworld.calm','bed'),
 ('62489','forest','An October night in open country. THE Overworld night bed.','bed.overworld.night','bed'),
 ('520959','forest','Night ambience, short — the alternate night bed.','bed.overworld.night2','bed'),
 ('638404','forest','The border between forest and farm field at dawn. The seam bed.','bed.border','bed'),
 ('758395','forest','Leaves rustling.','sfx.leaves','sfx'),
 ('765491','forest','Rustling bush leaves. NONCOMMERCIAL.','sfx.bush','sfx'),
 ('95263','forest','Tree creak.','sfx.tree.creak','sfx'),
 ('85433','forest','A branch snap. AIFF — runtime copy required.','sfx.branch','sfx'),
 ('811529','forest','Branch snaps and crackles — also the Stalker moving through cover.','sfx.branch.crackle','sfx'),
 ('396012','forest','A short grass rustle.','sfx.grass','sfx'),
 # ---- farmlands -------------------------------------------------------------------
 ('488067','farmlands','Farm ambience, wide and open. THE Farmlands day bed.','bed.farm.day','bed'),
 ('488066','farmlands','Farm ambience, second take — the alternate day bed.','bed.farm.day2','bed'),
 ('584590','farmlands','Night farm fields. THE Farmlands night bed.','bed.farm.night','bed'),
 ('523374','farmlands','Open field summer wind.','bed.farm.wind','bed'),
 ('454364','farmlands','Wind through dry corn stalks. The wheat-field layer of the journey.','bed.farm.crop','bed'),
 ('542254','farmlands','Tall grass rustling — close crop movement.','sfx.crop','sfx'),
 ('403978','farmlands','Crows calling from distant woods.','sfx.crows','sfx'),
 ('464764','farmlands','Birds, a crow, a distant road.','sfx.birds.road','sfx'),
 ('813114','farmlands','A single crow call. FLAC — runtime copy required.','sfx.crow','sfx'),
 ('344984','farmlands','An old tractor passing, far off. Rural infrastructure that still runs.','sfx.tractor','sfx'),
 ('570376','farmlands','Tractor driving past.','sfx.tractor2','sfx'),
 ('820267','farmlands','Distant dogs.','sfx.dogs','sfx'),
 ('507465','farmlands','Four quiet distant clangs. AIFF — runtime copy required.','sfx.clang.far','sfx'),
 ('507469','farmlands','Three low metal clangs with reverb. AIFF — runtime copy required.','sfx.clang.low','sfx'),
 ('333988','farmlands','Distant falling glass and metal — something gave way, out of sight.','sfx.collapse.far','sfx'),
 ('80450','farmlands','Metal creaking and falling. NONCOMMERCIAL.','sfx.metal.fall','sfx'),
 ('124122','farmlands','Rusted metal spokes turning. NONCOMMERCIAL.','sfx.rust.turn','sfx'),
 # ---- animals ----------------------------------------------------------------------
 ('867553','animals','Cow.','sfx.animal.cow','sfx'),
 ('692900','animals','Sheep.','sfx.animal.sheep','sfx'),
 ('456803','animals','Chicken.','sfx.animal.chicken','sfx'),
 ('418428','animals','Horse. NONCOMMERCIAL — and the only horse in the library.','sfx.animal.horse','sfx'),
 # ---- weather ----------------------------------------------------------------------
 ('96729','weather','Light rain.','bed.rain.light','bed'),
 ('640651','weather','Heavy rain and gutter.','bed.rain.heavy','bed'),
 ('823199','weather','Rain on a plastic roof — heard from inside.','bed.rain.roof','bed'),
 ('751720','weather','Storm wind heard as a room tone. Interior during weather.','bed.storm.room','bed'),
 ('238743','weather','Distant thunder over a suburb.','sfx.thunder.sub','sfx'),
 ('398206','weather','Distant thunder, open country.','sfx.thunder.far','sfx'),
 ('16950','weather','Open wind bed. NONCOMMERCIAL.','bed.wind.open','bed'),
 ('361487','weather','A wind gust whipping past.','sfx.gust','sfx'),
 # ---- water ------------------------------------------------------------------------
 ('325324','water','A stream. The Farmland watercourse bed.','bed.water.stream','bed'),
 ('536124','water','A second stream take.','bed.water.stream2','bed'),
 ('271336','water','Fast dripping water.','sfx.drip.fast','sfx'),
 ('442480','water','Water dripping under a bridge — drainage, culverts.','sfx.drip.slow','sfx'),
 ('666290','water','Water steaming on a hot surface.','sfx.steam','sfx'),
 # ---- suburbia ----------------------------------------------------------------------
 ('481964','suburbia','Quiet neighbourhood, light wind, no people. THE Suburbia day bed.','bed.sub.day','bed'),
 ('135074','suburbia','Residential street with quiet birds — the alternate day bed.','bed.sub.day2','bed'),
 ('535761','suburbia','Neighbourhood night: crickets and an electrical hum. THE Suburbia night bed.','bed.sub.night','bed'),
 ('428844','suburbia','Distant traffic from a rooftop — the city that is still out there.','bed.sub.traffic','bed'),
 ('669729','suburbia','A single car passing, far off.','sfx.car.pass','sfx'),
 ('614573','suburbia','Muffled voices through a wall. No words are legible.','sfx.voices.muffled','sfx'),
 # ---- electrical / hum ---------------------------------------------------------------
 ('553075','electrical','Short mechanism buzz, authored as a loop. Lights and fittings.','bed.hum.buzz','bed'),
 ('740110','electrical','Large refrigerator compressor hum — kitchens.','bed.hum.fridge','bed'),
 ('72091','electrical','Low-frequency humming.','bed.hum.low','bed'),
 ('865628','electrical','Mechanical drone texture, seamless loop.','bed.hum.mech','bed'),
 ('816619','electrical','High-tension power line. NONCOMMERCIAL.','bed.hum.powerline','bed'),
 ('407233','electrical','An electrical arc / crackle.','sfx.electric','sfx'),
 ('799662','electrical','Analog video hum — the Suburbia CRT layer.','bed.hum.crt','bed'),
 # ---- rift / reality distortion ---------------------------------------------------------
 ('745231','rift','Radio static. The Rift interference layer.','bed.rift.static','bed'),
 ('852315','rift','Organic pulsing drone, authored as a loop. The Rift body.','bed.rift.pulse','bed'),
 ('344612','rift','A distorted synth drone that fades in and out.','bed.rift.drone','bed'),
 ('211603','rift','Eerie background space tone.','bed.rift.space','bed'),
 ('826582','rift','Four otherworldly transitions. NONCOMMERCIAL.','sfx.rift.transition','sfx'),
 ('562643','rift','Instrument distortion — a familiar sound coming apart.','sfx.rift.distort','sfx'),
 ('381223','rift','Distorted scraping. NONCOMMERCIAL.','sfx.rift.scrape','sfx'),
 ('90335','rift','A short glitch.','sfx.rift.glitch','sfx'),
 ('30611','rift','A distorted music box — memory that has been reconstructed wrongly.','sfx.rift.musicbox','sfx'),
 ('61617','rift','Designed whoosh-and-knock texture.','sfx.rift.knack','sfx'),
 # ---- stalker -----------------------------------------------------------------------------
 ('383724','stalker','Heavy walking. The Stalker approach steps.','step.stalker','step'),
 ('152004','stalker','Loud heavy footsteps. The Stalker at close range.','step.stalker.near','step'),
 ('788342','stalker','Clothing moving as something walks. Sliced into cloth ticks.','step.cloth','step'),
 ('195572','stalker','Creature breath.','sfx.stalker.breath','sfx'),
 ('369294','stalker','Slow, wrong breathing.','sfx.stalker.breath2','sfx'),
 ('121584','stalker','A single exhaled breath, close.','sfx.stalker.breath3','sfx'),
 ('528506','stalker','Creature horror texture. NONCOMMERCIAL.','sfx.stalker.creature','sfx'),
 # ---- horror tension ----------------------------------------------------------------------
 ('826597','tension','Dark tension drone.','bed.tension.dark','bed'),
 ('845551','tension','High tension pulsing drone.','bed.tension.pulse','bed'),
 ('744080','tension','A long horror drone.','bed.tension.long','bed'),
 ('628917','tension','Drone 003 — a two-minute bed.','bed.tension.slow','bed'),
 ('81034','tension','Cello bass drone — the closest thing in the library to music.','bed.tension.cello','bed'),
 ('355738','tension','A three-and-a-half minute drone.','bed.tension.deep','bed'),
 ('867568','tension','Wind chimes over a deep drone.','bed.tension.chime','bed'),
 ('548621','tension','Reversed piano, nearly three minutes.','bed.tension.piano','bed'),
 ('529138','tension','Deep ambient pulses with drums.','bed.tension.pulsedrum','bed'),
 ('540967','tension','A short eerie atmosphere.','sfx.eerie','sfx'),
 ('554110','tension','Long horror ambience drone. NONCOMMERCIAL.','bed.tension.nc1','bed'),
 ('555179','tension','Creepy horror ambient drone. NONCOMMERCIAL.','bed.tension.nc2','bed'),
 ('567662','tension','An odd bass swell.','sfx.swell.odd','sfx'),
 ('192574','tension','A long bass swell. AIFF — runtime copy required.','sfx.swell.long','sfx'),
 ('218354','tension','A short cinematic swell.','sfx.swell.short','sfx'),
 ('443968','tension','Distorted gated piano swell. NONCOMMERCIAL.','sfx.swell.piano','sfx'),
 ('612641','tension','Heartbeat rising and falling. NONCOMMERCIAL.','bed.heartbeat','bed'),
 # ---- blood night --------------------------------------------------------------------------
 ('473725','bloodnight','Low noise rumble. The Blood Night floor.','bed.blood.rumble','bed'),
 ('16947','bloodnight','Deep earth rumble. NONCOMMERCIAL.','bed.blood.earth','bed'),
 ('320788','bloodnight','Distant explosions — something happening a long way off.','bed.blood.far','bed'),
 ('324277','bloodnight','A single distant explosion.','sfx.blast.far','sfx'),
 ('529566','bloodnight','A short distant rumble.','sfx.rumble.short','sfx'),
 # ---- behemoth -----------------------------------------------------------------------------
 ('456854','behemoth','A far-off growl. The Behemoth heard before it is seen.','sfx.behemoth.far','sfx'),
 ('837799','behemoth','A large, wet, non-human roar.','sfx.behemoth.roar','sfx'),
 ('841961','behemoth','A heavy reverberant roar.','sfx.behemoth.roar2','sfx'),
 ('261147','behemoth','A monster heard at distance.','sfx.behemoth.dist','sfx'),
 ('181374','behemoth','A broken attempt at a voice.','sfx.behemoth.voice','sfx'),
 # ---- haven disappearance --------------------------------------------------------------------
 ('853575','vanish','Low drone with a slow metallic shift. The Haven dissolve floor.','bed.vanish.low','bed'),
 ('810737','vanish','A long airy whoosh — the room letting go.','sfx.vanish.air','sfx'),
 ('73263','vanish','A soft whoosh.','sfx.whoosh.soft','sfx'),
 # ---- finale ---------------------------------------------------------------------------------
 ('867251','finale','Deep rumbling drone with enormous reverb. THE finale floor.','bed.finale.deep','bed'),
 ('321812','finale','Cinematic deep bass rumble. The finale scale layer.','bed.finale.rumble','bed'),
 ('529620','finale','A massive structure bending. Something that size moving.','sfx.finale.bend','sfx'),
 ('653294','finale','A big structural collision heard from inside.','sfx.finale.collide','sfx'),
 ('845339','finale','Air moving in bursts — pressure rather than a voice.','bed.finale.air','bed'),
 ('856174','finale','A subterranean sub-bass drop.','sfx.finale.drop','sfx'),
 ('754422','finale','Deep cinematic impact. The one strike on the face beat.','sfx.finale.strike','sfx'),
 ('754424','finale','Deep cinematic impact, alternate.','sfx.finale.strike2','sfx'),
 # ---- ui / interaction -------------------------------------------------------------------------
 ('342898','ui','Menu click.','sfx.ui.click','sfx'),
 ('687108','ui','A longer button click.','sfx.ui.click2','sfx'),
 ('327738','ui','An error / refusal tick.','sfx.ui.deny','sfx'),
 ('868506','ui','Item pickup pop.','sfx.ui.pickup','sfx'),
 ('761011','ui','A small cap pop — chest lid, container open.','sfx.ui.pop','sfx'),
 # ---- impacts and stings ---------------------------------------------------------------------
 ('162850','impact','Cinema boom impact.','sfx.impact.boom','sfx'),
 ('475005','impact','Synth bass drop impact.','sfx.impact.drop','sfx'),
 ('475040','impact','Percussion hit.','sfx.impact.perc','sfx'),
 ('388950','impact','Deep soft bassy hit.','sfx.impact.soft','sfx'),
 ('825797','impact','Bass kick explosion.','sfx.impact.kick','sfx'),
 ('177126','impact','Cinematic drum hit. NONCOMMERCIAL.','sfx.impact.drum','sfx'),
 # ---- voices, whispers, breath -------------------------------------------------------------------
 ('193818','voice','Four overlapping whispers. No words legible.','sfx.whisper.four','sfx'),
 ('730965','voice','Close whispering. No words legible.','sfx.whisper.close','sfx'),
 ('7998','voice','Human breathing.','sfx.breath.player','sfx'),
 ('512741','voice','Breathing that speeds up.','sfx.breath.fast','sfx'),
 ('554735','voice','Quiet respiration.','sfx.breath.quiet','sfx'),
 # ---- catalogued, not wired ------------------------------------------------------------------------
 ('118083','unwired','Unidentified field recording. SAMPLING+ — quarantined, not wired.',None,'sfx'),
 ('636777','unwired','Unlabelled field recording; content not identifiable from metadata.',None,'sfx'),
 ('503270','unwired','A whispered English sentence. STORY.md section 13 forbids legible speech.',None,'sfx'),
 ('242933','unwired','A child laughing. Too explicit a horror signal for this game.',None,'sfx'),
]
